# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.
controller:
  metricsBindAddr: "127.0.0.1:8080"
  leaderElection: false
  metricsSink: "noop"
  enableSafeguards: false
  notifiers:
    common:
      clusterName: colima
    noop:
      enabled: true
    slack:
      enabled: false
      tokenFilepath: ""
    http:
      enabled: false
      url: ""
      headersFilepath: ""
      headers: []
  deleteOnly: false
  imagePullSecrets: ""
  defaultDuration: 1h
  expiredDisruptionGCDelay: 10m
  webhook:
    certDir: "local/certDir"
    host: ""
    port: 9443
injector:
  image: k8s.io/chaos-injector:latest
  serviceAccount: "chaos-injector"
  chaosNamespace: "chaos-engineering"
  dnsDisruption:
    dnsServer: ""
    kubeDns: "all"
handler:
  enabled: true
  image: k8s.io/chaos-handler:latest
  timeout: "1m"
