# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-demo-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-curl-2
  namespace: chaos-demo-2
  labels:
    app: demo-curl-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-curl-2
  template:
    metadata:
      labels:
        app: demo-curl-2
    spec:
      containers:
        - name: dummyd
          image: ubuntu:bionic-20220128
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 1; done"]
