# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-2
  namespace: chaos-demo
  labels:
    app: demo-nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx-2
  template:
    metadata:
      labels:
        app: demo-nginx-2
    spec:
      tolerations:
        - key: "node"
          operator: "Equal"
          effect: "NoSchedule"
          value: "nodeless"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/nodeless
                    operator: Exists
      containers:
        - name: nginx
          image: nginx:1.21.6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-curl
  namespace: chaos-demo
  labels:
    app: demo-curl
spec:
  selector:
    matchLabels:
      app: demo-curl
  template:
    metadata:
      labels:
        app: demo-curl
        chaos.datadoghq.com/disrupt-on-init: "true"
    spec:
      tolerations:
        - key: "node"
          operator: "Equal"
          effect: "NoSchedule"
          value: "nodeless"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/nodeless
                    operator: Exists
      containers:
        - name: curlc
          image: curlimages/curl:7.68.0
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://demo.chaos-demo.svc.cluster.local:8080; curl -vvv https://google.com; sleep 10; done",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: demo-2
  namespace: chaos-demo
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: demo-nginx-2
