# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

# Transmits network to demo-2 service instead of demo

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: dns
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  duration: 1h
  staticTargeting: false
  dns: # disrupt DNS resolutions by faking results
    - hostname: demo.chaos-demo.svc.cluster.local # record hostname which should be faked
      record:
        type: CNAME # return an A record
        value: demo-2.chaos-demo.svc.cluster.local # list of IPs to return (will be round-robined)
    - hostname: demo.chaos-demo.svc.cluster.local # record hostname which should be faked
      record:
        type: A # return an A recordf
        value: 10.129.154.61
