# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

# Transmits network to demo-2 service instead of demo

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: ingress-network-disruption-on-service
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  duration: 1h
  network: # disrupt DNS resolutions by faking results
    services: # optional, list of source services to filter on
      - name: demo # service name
        namespace: chaos-demo # service namespace
        flow: ingress
    drop: 100
