# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

# Transmits network to demo-2 service instead of demo

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: ingress-network-disruption-on-hosts
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-nginx
  count: 1
  staticTargeting: false
  network: # disrupt DNS resolutions by faking results
    hosts:
      - port: 80 # optional, port to drop packets on
        protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
        flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
    drop: 100
