# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026 Datadog, Inc.

version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gocritic
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter:|and that stutters;|unexported-return:|var-naming:'
      - linters:
          - staticcheck
        text: 'at least one file in a package should have a package comment'
      - path: (.+)\.go$
        text: Subprocess launch(ed with variable|ing should be audited)
      - path: (.+)\.go$
        text: Expect file permissions to be 0600 or less
      - path: (.+)\.go$
        text: Blocklisted import `crypto/md5`
      - path: (.+)\.go$
        text: weak cryptographic primitive
      - path: (.+)\.go$
        text: weak random number generator
      - path: (.+)\.go$
        text: memory aliasing in for loop
      - path: (.+)\.go$
        text: file inclusion via variable
      - path: (.+)\.go$
        text: integer overflow conversion
      - path: (.+)\.go$
        text: (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    paths:
      - .*mock.*\.go$
      - mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*mock.*\.go$
      - mocks
      - third_party$
      - builtin$
      - examples$
