run:
  skip-files:
    - api/v1beta1/zz_generated.deepcopy.go
    - ".*_test.go"
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
