# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2022 Datadog, Inc.

run:
  skip-files:
    - api/v1beta1/zz_generated.deepcopy.go
    - ".*_test.go"
    - cpuset/*
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - goconst
    - godox
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
    - gocritic
issues:
  exclude-use-default: false
  exclude:
    # gosec
    - Subprocess launch(ed with variable|ing should be audited)
    - Expect file permissions to be 0600 or less
    - Blocklisted import `crypto/md5`
    - weak cryptographic primitive
    - weak random number generator
    - memory aliasing in for loop
    - file inclusion via variable
    # stylecheck
    - at least one file in a package should have a package comment
    # golint
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # revive
    - and that stutters
