# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026 Datadog, Inc.

version: "2"

run:
  tests: false

linters:
  default: none
  enable:
    # default linters
    - errcheck
    # gosimple merged into staticcheck in v2
    - govet
    - ineffassign
    - staticcheck
    # typecheck is built into v2 core, cannot be enabled/disabled
    - unused
    # extra linters
    - bodyclose
    - dogsled
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    # stylecheck merged into staticcheck in v2
    - unconvert
    - unparam
    - whitespace
    - wsl
    - gocritic
  exclusions:
    generated: lax  # match v1 behavior (v2 default is strict)
    paths:
      - mocks
      - '.*mock.*\.go$'
    rules:
      # gosec exclusions
      - linters:
          - gosec
        text: 'Subprocess launch(ed with variable|ing should be audited)'
      - linters:
          - gosec
        text: 'Expect file permissions to be 0600 or less'
      - linters:
          - gosec
        text: 'Blocklisted import `crypto/md5`'
      - linters:
          - gosec
        text: 'weak cryptographic primitive'
      - linters:
          - gosec
        text: 'weak random number generator'
      - linters:
          - gosec
        text: 'memory aliasing in for loop'
      - linters:
          - gosec
        text: 'file inclusion via variable'
      - linters:
          - gosec
        text: 'integer overflow conversion'
      # revive exclusions
      - linters:
          - revive
        text: 'unused-parameter:|and that stutters;|unexported-return:'
      # staticcheck exclusions (was stylecheck in v1)
      - linters:
          - staticcheck
        text: 'at least one file in a package should have a package comment'
      # comment-related exclusions (was golint in v1)
      - linters:
          - revive
        text: '(comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)'

formatters:
  enable:
    - gofmt
    - goimports

output:
  sort-results: true
