# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  pod-template.json: |
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "generateName": "PLACEHOLDER",
        "namespace": "PLACEHOLDER",
        "nodeName": "PLACEHOLDER"
      },
      "spec": {
        "priorityClassName": "chaos-controller-high-priority",
        "restartPolicy": "Never",
        "containers": [
          {
            "name": "injector",
            "image": "PLACEHOLDER",
            "imagePullPolicy": "IfNotPresent",
            "args": [],
            "env": [
              {
                "name": "CHAOS_INJECTOR_MOUNT_HOST",
                "value": "/mnt/host/"
              },
              {
                "name": "CHAOS_INJECTOR_MOUNT_PROC",
                "value": "/mnt/host/proc/"
              },
              {
                "name": "CHAOS_INJECTOR_MOUNT_SYSRQ",
                "value": "/mnt/sysrq"
              },
              {
                "name": "CHAOS_INJECTOR_MOUNT_SYSRQ_TRIGGER",
                "value": "/mnt/sysrq-trigger"
              },
              {
                "name": "CHAOS_INJECTOR_MOUNT_CGROUP",
                "value": "/mnt/cgroup/"
              }
            ],
            "volumeMounts": [
              {
                "name": "run",
                "mountPath": "/run"
              },
              {
                "name": "sysrq",
                "mountPath": "/mnt/sysrq"
              },
              {
                "name": "sysrq-trigger",
                "mountPath": "/mnt/sysrq-trigger"
              },
              {
                "name": "cgroup",
                "mountPath": "/mnt/cgroup/"
              },
              {
                "name": "host",
                "mountPath": "/mnt/host/",
                "readOnly": true
              }
            ],
            "securityContext": {
              "privileged": true
            },
            "resources": {
              "limits": {
                "memory": 0,
                "cpu": 0
              },
              "requests": {
                "memory": 0,
                "cpu": 0
              }
            }
          }
        ],
        "volumes": [
          {
            "name": "run",
            "hostPath": {
              "path": "/run",
              "type": "Directory"
            }
          },
          {
            "name": "proc",
            "hostPath": {
              "path": "/proc",
              "type": "Directory"
            }
          },
          {
            "name": "sysrq",
            "hostPath": {
              "path": "/proc/sys/kernel/sysrq",
              "type": "File"
            }
          },
          {
            "name": "sysrq-trigger",
            "hostPath": {
              "path": "/proc/sysrq-trigger",
              "type": "File"
            }
          },
          {
            "name": "cgroup",
            "hostPath": {
              "path": "/sys/fs/cgroup",
              "type": "Directory"
            }
          },
          {
            "name": "host",
            "hostPath": {
              "path": "/",
              "type": "Directory"
            }
          }
        ]
      }
    }
