apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: networkfailureinjections.chaos.datadoghq.com
spec:
  group: chaos.datadoghq.com
  names:
    kind: NetworkFailureInjection
    plural: networkfailureinjections
    shortNames:
    - nfi
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            failure:
              properties:
                host:
                  type: string
                port:
                  format: int64
                  type: integer
                probability:
                  format: int64
                  type: integer
                protocol:
                  type: string
              required:
              - port
              - probability
              - protocol
              type: object
            numPodsToTarget:
              format: int64
              minimum: 0
              type: integer
            selector:
              type: object
          required:
          - failure
          - selector
          type: object
        status:
          properties:
            finalizing:
              type: boolean
            injected:
              type: boolean
            pods:
              items:
                type: string
              type: array
          required:
          - finalizing
          - injected
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
