apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodefailureinjections.chaos.datadoghq.com
spec:
  group: chaos.datadoghq.com
  names:
    kind: NodeFailureInjection
    plural: nodefailureinjections
    shortNames:
    - nofi
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            quantity:
              description: Number of pods to target, defaults to 1 if not specifiedd
              format: int64
              type: integer
            selector:
              type: object
          required:
          - selector
          type: object
        status:
          properties:
            injected:
              format: int64
              type: integer
            nodeNames:
              type: object
          required:
          - injected
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
