# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

{{- if not .Values.skipNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.chaosNamespace }}"
{{- end }}
