# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-controller
subjects:
  - kind: ServiceAccount
    name: chaos-controller
    namespace: "{{ .Values.chaosNamespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-controller-leader-election
  namespace: "{{ .Values.chaosNamespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-controller-leader-election
subjects:
  - kind: ServiceAccount
    name: chaos-controller
    namespace: "{{ .Values.chaosNamespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-controller-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-controller-proxy
subjects:
  - kind: ServiceAccount
    name: chaos-controller
    namespace: "{{ .Values.chaosNamespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-injector
subjects:
  - kind: ServiceAccount
    name: chaos-injector
    namespace: "{{ .Values.chaosNamespace }}"
