# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-controller
  namespace: chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.injector.serviceAccount }}
  namespace: {{ .Values.injector.serviceAccountNamespace }}
