# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

apiVersion: v1
kind: Service
metadata:
  name: chaos-controller-metrics-service
  namespace: "{{ .Values.chaosNamespace }}"
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app: chaos-controller
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-controller-webhook-service
  namespace: "{{ .Values.chaosNamespace }}"
spec:
  ports:
    - name: webhook-server
      port: 443
      targetPort: webhook-server
  selector:
    app: chaos-controller
