
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-datadoghq-com-v1beta1-disruption
  failurePolicy: Fail
  name: vdisruption.kb.io
  rules:
  - apiGroups:
    - chaos.datadoghq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - disruptions
