// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package disruptionlistener

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"
)

// DisruptionListenerClientMock is an autogenerated mock type for the DisruptionListenerClient type
type DisruptionListenerClientMock struct {
	mock.Mock
}

type DisruptionListenerClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DisruptionListenerClientMock) EXPECT() *DisruptionListenerClientMock_Expecter {
	return &DisruptionListenerClientMock_Expecter{mock: &_m.Mock}
}

// Disrupt provides a mock function with given fields: ctx, in, opts
func (_m *DisruptionListenerClientMock) Disrupt(ctx context.Context, in *DisruptionSpec, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Disrupt")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DisruptionSpec, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DisruptionSpec, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DisruptionSpec, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisruptionListenerClientMock_Disrupt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disrupt'
type DisruptionListenerClientMock_Disrupt_Call struct {
	*mock.Call
}

// Disrupt is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DisruptionSpec
//   - opts ...grpc.CallOption
func (_e *DisruptionListenerClientMock_Expecter) Disrupt(ctx interface{}, in interface{}, opts ...interface{}) *DisruptionListenerClientMock_Disrupt_Call {
	return &DisruptionListenerClientMock_Disrupt_Call{Call: _e.mock.On("Disrupt",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *DisruptionListenerClientMock_Disrupt_Call) Run(run func(ctx context.Context, in *DisruptionSpec, opts ...grpc.CallOption)) *DisruptionListenerClientMock_Disrupt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*DisruptionSpec), variadicArgs...)
	})
	return _c
}

func (_c *DisruptionListenerClientMock_Disrupt_Call) Return(_a0 *emptypb.Empty, _a1 error) *DisruptionListenerClientMock_Disrupt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DisruptionListenerClientMock_Disrupt_Call) RunAndReturn(run func(context.Context, *DisruptionSpec, ...grpc.CallOption) (*emptypb.Empty, error)) *DisruptionListenerClientMock_Disrupt_Call {
	_c.Call.Return(run)
	return _c
}

// ResetDisruptions provides a mock function with given fields: ctx, in, opts
func (_m *DisruptionListenerClientMock) ResetDisruptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResetDisruptions")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisruptionListenerClientMock_ResetDisruptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetDisruptions'
type DisruptionListenerClientMock_ResetDisruptions_Call struct {
	*mock.Call
}

// ResetDisruptions is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *DisruptionListenerClientMock_Expecter) ResetDisruptions(ctx interface{}, in interface{}, opts ...interface{}) *DisruptionListenerClientMock_ResetDisruptions_Call {
	return &DisruptionListenerClientMock_ResetDisruptions_Call{Call: _e.mock.On("ResetDisruptions",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *DisruptionListenerClientMock_ResetDisruptions_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *DisruptionListenerClientMock_ResetDisruptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *DisruptionListenerClientMock_ResetDisruptions_Call) Return(_a0 *emptypb.Empty, _a1 error) *DisruptionListenerClientMock_ResetDisruptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DisruptionListenerClientMock_ResetDisruptions_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *DisruptionListenerClientMock_ResetDisruptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewDisruptionListenerClientMock creates a new instance of DisruptionListenerClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisruptionListenerClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisruptionListenerClientMock {
	mock := &DisruptionListenerClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
