// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: disruptionlistener.proto

package disruptionlistener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisruptionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointSpec        `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisruptionSpec) Reset() {
	*x = DisruptionSpec{}
	mi := &file_disruptionlistener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisruptionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisruptionSpec) ProtoMessage() {}

func (x *DisruptionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_disruptionlistener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisruptionSpec.ProtoReflect.Descriptor instead.
func (*DisruptionSpec) Descriptor() ([]byte, []int) {
	return file_disruptionlistener_proto_rawDescGZIP(), []int{0}
}

func (x *DisruptionSpec) GetEndpoints() []*EndpointSpec {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type EndpointSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEndpoint string                 `protobuf:"bytes,1,opt,name=targetEndpoint,proto3" json:"targetEndpoint,omitempty"`
	Alterations    []*AlterationSpec      `protobuf:"bytes,2,rep,name=alterations,proto3" json:"alterations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EndpointSpec) Reset() {
	*x = EndpointSpec{}
	mi := &file_disruptionlistener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSpec) ProtoMessage() {}

func (x *EndpointSpec) ProtoReflect() protoreflect.Message {
	mi := &file_disruptionlistener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSpec.ProtoReflect.Descriptor instead.
func (*EndpointSpec) Descriptor() ([]byte, []int) {
	return file_disruptionlistener_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointSpec) GetTargetEndpoint() string {
	if x != nil {
		return x.TargetEndpoint
	}
	return ""
}

func (x *EndpointSpec) GetAlterations() []*AlterationSpec {
	if x != nil {
		return x.Alterations
	}
	return nil
}

type AlterationSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorToReturn    string                 `protobuf:"bytes,1,opt,name=errorToReturn,proto3" json:"errorToReturn,omitempty"`
	OverrideToReturn string                 `protobuf:"bytes,2,opt,name=overrideToReturn,proto3" json:"overrideToReturn,omitempty"`
	QueryPercent     int32                  `protobuf:"varint,3,opt,name=queryPercent,proto3" json:"queryPercent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AlterationSpec) Reset() {
	*x = AlterationSpec{}
	mi := &file_disruptionlistener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterationSpec) ProtoMessage() {}

func (x *AlterationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_disruptionlistener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterationSpec.ProtoReflect.Descriptor instead.
func (*AlterationSpec) Descriptor() ([]byte, []int) {
	return file_disruptionlistener_proto_rawDescGZIP(), []int{2}
}

func (x *AlterationSpec) GetErrorToReturn() string {
	if x != nil {
		return x.ErrorToReturn
	}
	return ""
}

func (x *AlterationSpec) GetOverrideToReturn() string {
	if x != nil {
		return x.OverrideToReturn
	}
	return ""
}

func (x *AlterationSpec) GetQueryPercent() int32 {
	if x != nil {
		return x.QueryPercent
	}
	return 0
}

var File_disruptionlistener_proto protoreflect.FileDescriptor

const file_disruptionlistener_proto_rawDesc = "" +
	"\n" +
	"\x18disruptionlistener.proto\x12\x12disruptionlistener\x1a\x1bgoogle/protobuf/empty.proto\"P\n" +
	"\x0eDisruptionSpec\x12>\n" +
	"\tendpoints\x18\x01 \x03(\v2 .disruptionlistener.EndpointSpecR\tendpoints\"|\n" +
	"\fEndpointSpec\x12&\n" +
	"\x0etargetEndpoint\x18\x01 \x01(\tR\x0etargetEndpoint\x12D\n" +
	"\valterations\x18\x02 \x03(\v2\".disruptionlistener.AlterationSpecR\valterations\"\x86\x01\n" +
	"\x0eAlterationSpec\x12$\n" +
	"\rerrorToReturn\x18\x01 \x01(\tR\rerrorToReturn\x12*\n" +
	"\x10overrideToReturn\x18\x02 \x01(\tR\x10overrideToReturn\x12\"\n" +
	"\fqueryPercent\x18\x03 \x01(\x05R\fqueryPercent2\xa3\x01\n" +
	"\x12DisruptionListener\x12G\n" +
	"\aDisrupt\x12\".disruptionlistener.DisruptionSpec\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x10ResetDisruptions\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\x16Z\x14./disruptionlistenerb\x06proto3"

var (
	file_disruptionlistener_proto_rawDescOnce sync.Once
	file_disruptionlistener_proto_rawDescData []byte
)

func file_disruptionlistener_proto_rawDescGZIP() []byte {
	file_disruptionlistener_proto_rawDescOnce.Do(func() {
		file_disruptionlistener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disruptionlistener_proto_rawDesc), len(file_disruptionlistener_proto_rawDesc)))
	})
	return file_disruptionlistener_proto_rawDescData
}

var file_disruptionlistener_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_disruptionlistener_proto_goTypes = []any{
	(*DisruptionSpec)(nil), // 0: disruptionlistener.DisruptionSpec
	(*EndpointSpec)(nil),   // 1: disruptionlistener.EndpointSpec
	(*AlterationSpec)(nil), // 2: disruptionlistener.AlterationSpec
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_disruptionlistener_proto_depIdxs = []int32{
	1, // 0: disruptionlistener.DisruptionSpec.endpoints:type_name -> disruptionlistener.EndpointSpec
	2, // 1: disruptionlistener.EndpointSpec.alterations:type_name -> disruptionlistener.AlterationSpec
	0, // 2: disruptionlistener.DisruptionListener.Disrupt:input_type -> disruptionlistener.DisruptionSpec
	3, // 3: disruptionlistener.DisruptionListener.ResetDisruptions:input_type -> google.protobuf.Empty
	3, // 4: disruptionlistener.DisruptionListener.Disrupt:output_type -> google.protobuf.Empty
	3, // 5: disruptionlistener.DisruptionListener.ResetDisruptions:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_disruptionlistener_proto_init() }
func file_disruptionlistener_proto_init() {
	if File_disruptionlistener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disruptionlistener_proto_rawDesc), len(file_disruptionlistener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_disruptionlistener_proto_goTypes,
		DependencyIndexes: file_disruptionlistener_proto_depIdxs,
		MessageInfos:      file_disruptionlistener_proto_msgTypes,
	}.Build()
	File_disruptionlistener_proto = out.File
	file_disruptionlistener_proto_goTypes = nil
	file_disruptionlistener_proto_depIdxs = nil
}
