// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package injector

import mock "github.com/stretchr/testify/mock"

// CPUStressArgsBuilderMock is an autogenerated mock type for the CPUStressArgsBuilder type
type CPUStressArgsBuilderMock struct {
	mock.Mock
}

type CPUStressArgsBuilderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CPUStressArgsBuilderMock) EXPECT() *CPUStressArgsBuilderMock_Expecter {
	return &CPUStressArgsBuilderMock_Expecter{mock: &_m.Mock}
}

// GenerateArgs provides a mock function with given fields: _a0
func (_m *CPUStressArgsBuilderMock) GenerateArgs(_a0 int) []string {
	ret := _m.Called(_a0)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// CPUStressArgsBuilderMock_GenerateArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateArgs'
type CPUStressArgsBuilderMock_GenerateArgs_Call struct {
	*mock.Call
}

// GenerateArgs is a helper method to define mock.On call
//   - _a0 int
func (_e *CPUStressArgsBuilderMock_Expecter) GenerateArgs(_a0 interface{}) *CPUStressArgsBuilderMock_GenerateArgs_Call {
	return &CPUStressArgsBuilderMock_GenerateArgs_Call{Call: _e.mock.On("GenerateArgs", _a0)}
}

func (_c *CPUStressArgsBuilderMock_GenerateArgs_Call) Run(run func(_a0 int)) *CPUStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *CPUStressArgsBuilderMock_GenerateArgs_Call) Return(_a0 []string) *CPUStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CPUStressArgsBuilderMock_GenerateArgs_Call) RunAndReturn(run func(int) []string) *CPUStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCPUStressArgsBuilderMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewCPUStressArgsBuilderMock creates a new instance of CPUStressArgsBuilderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCPUStressArgsBuilderMock(t mockConstructorTestingTNewCPUStressArgsBuilderMock) *CPUStressArgsBuilderMock {
	mock := &CPUStressArgsBuilderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
