// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

package injector

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MemoryStressArgsBuilderMock is an autogenerated mock type for the MemoryStressArgsBuilder type
type MemoryStressArgsBuilderMock struct {
	mock.Mock
}

type MemoryStressArgsBuilderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MemoryStressArgsBuilderMock) EXPECT() *MemoryStressArgsBuilderMock_Expecter {
	return &MemoryStressArgsBuilderMock_Expecter{mock: &_m.Mock}
}

// GenerateArgs provides a mock function with given fields: targetPercent, rampDuration
func (_m *MemoryStressArgsBuilderMock) GenerateArgs(targetPercent int, rampDuration time.Duration) []string {
	ret := _m.Called(targetPercent, rampDuration)

	if len(ret) == 0 {
		panic("no return value specified for GenerateArgs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(int, time.Duration) []string); ok {
		r0 = rf(targetPercent, rampDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MemoryStressArgsBuilderMock_GenerateArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateArgs'
type MemoryStressArgsBuilderMock_GenerateArgs_Call struct {
	*mock.Call
}

// GenerateArgs is a helper method to define mock.On call
//   - targetPercent int
//   - rampDuration time.Duration
func (_e *MemoryStressArgsBuilderMock_Expecter) GenerateArgs(targetPercent interface{}, rampDuration interface{}) *MemoryStressArgsBuilderMock_GenerateArgs_Call {
	return &MemoryStressArgsBuilderMock_GenerateArgs_Call{Call: _e.mock.On("GenerateArgs", targetPercent, rampDuration)}
}

func (_c *MemoryStressArgsBuilderMock_GenerateArgs_Call) Run(run func(targetPercent int, rampDuration time.Duration)) *MemoryStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(time.Duration))
	})
	return _c
}

func (_c *MemoryStressArgsBuilderMock_GenerateArgs_Call) Return(_a0 []string) *MemoryStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemoryStressArgsBuilderMock_GenerateArgs_Call) RunAndReturn(run func(int, time.Duration) []string) *MemoryStressArgsBuilderMock_GenerateArgs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemoryStressArgsBuilderMock creates a new instance of MemoryStressArgsBuilderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemoryStressArgsBuilderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemoryStressArgsBuilderMock {
	mock := &MemoryStressArgsBuilderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
