# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: DisruptionCron
metadata:
  name: network-drop-2
  namespace: chaos-engineering
spec:
  schedule: "*/20 * * * *"
  targetResource:
    kind: deployment
    name: chaos-test-deployment
  disruptionTemplate:
    level: pod
    count: 1
    network:
      drop: 100 # percentage of outgoing packets to drop
    duration: 2m # disruption will time out after 10 seconds
