# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.io/chaos-dogfood-server"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
fullname: "chaos-dogfood-server"
namespace: "chaos-demo"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 50051
  name: "chaos-dogfood-server-service"

resources: {}

nodeSelector: {}

tolerations: []
