// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

package main

// getFileExtensions returns a map of file extensions to their comment characters
// Returns a new map to prevent external modification
func getFileExtensions() map[string]string {
	return map[string]string{
		".go":    "//",
		".c":     "//",
		".h":     "//",
		".proto": "//",
		".yaml":  "#",
		".yml":   "#",
		".py":    "#",
	}
}

// getAutoGeneratedPatterns returns file headers that indicate an auto-generated file
// Files with these patterns get a +2 line offset for header insertion
// Returns a new slice to prevent external modification
func getAutoGeneratedPatterns() []string {
	return []string{
		"//go:build !ignore_autogenerated\n",
		"// Code generated by mockery. DO NOT EDIT.\n",
		"// Code generated by client-gen. DO NOT EDIT.\n",
		"// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\n",
	}
}

// getShebangPattern returns the pattern that matches shebang lines
// Files starting with a shebang get a +1 line offset to preserve the shebang
func getShebangPattern() string {
	return "#!"
}

// getEncodingPatterns returns patterns that match Python PEP 263 encoding declarations
// These patterns detect encoding cookies like "# -*- coding: utf-8 -*-" or "# coding: utf-8"
// Python requires encoding declarations to be on line 1 or line 2
// Returns a new slice to prevent external modification
func getEncodingPatterns() []string {
	return []string{
		"coding:",
		"coding=",
	}
}

// getFilesToSkip returns the list of files that should not be checked/modified
// Returns a new slice to prevent external modification
func getFilesToSkip() []string {
	return []string{
		"api/v1beta1/zz_generated.deepcopy.go",
		"chart/templates/generated/chaos.datadoghq.com_disruptions.yaml",
		"chart/templates/generated/chaos.datadoghq.com_disruptioncrons.yaml",
		"chart/templates/generated/chaos.datadoghq.com_disruptionrollouts.yaml",
		"chart/templates/generated/role.yaml",
		"cpuset/cpuset.go",
		"ebpf/includes/bpf_endian.h",
		// Protobuf generated files - headers would be stripped on regeneration
		"dogfood/chaosdogfood/chaosdogfood.pb.go",
		"dogfood/chaosdogfood/chaosdogfood_grpc.pb.go",
		"grpc/disruptionlistener/disruptionlistener.pb.go",
		"grpc/disruptionlistener/disruptionlistener_grpc.pb.go",
	}
}

// getDirectoriesToSkip returns the list of directories that should not be traversed
// Returns a new slice to prevent external modification
func getDirectoriesToSkip() []string {
	return []string{
		"vendor",
		".venv",
		".git",
		"testdata",
	}
}
