# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo
  namespace: chaos-demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  namespace: chaos-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-2
  namespace: chaos-demo
  labels:
    app: demo-nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx-2
  template:
    metadata:
      labels:
        app: demo-nginx-2
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: chaos-demo
  labels:
    app: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-curl
  namespace: chaos-demo
  labels:
    app: demo-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-curl
  template:
    metadata:
      labels:
        app: demo-curl
    spec:
      containers:
        - name: curl
          image: bad-image
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://demo-hello.chaos-demo.svc.cluster.local:8080; echo '===============\n'; curl -vvv http://demo.chaos-demo.svc.cluster.local:8080; sleep 10; done",
            ]
          volumeMounts:
            - mountPath: /mnt/data
              name: data
          resources:
            limits:
              cpu: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-2
  namespace: chaos-demo
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: demo-nginx-2
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: chaos-demo
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: demo-nginx
