// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package cgroup

import mock "github.com/stretchr/testify/mock"

// allCGroupManagerMock is an autogenerated mock type for the allCGroupManager type
type allCGroupManagerMock struct {
	mock.Mock
}

type allCGroupManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *allCGroupManagerMock) EXPECT() *allCGroupManagerMock_Expecter {
	return &allCGroupManagerMock_Expecter{mock: &_m.Mock}
}

// EnterPid provides a mock function with given fields: cgroupPaths, pid
func (_m *allCGroupManagerMock) EnterPid(cgroupPaths map[string]string, pid int) error {
	ret := _m.Called(cgroupPaths, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string, int) error); ok {
		r0 = rf(cgroupPaths, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// allCGroupManagerMock_EnterPid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnterPid'
type allCGroupManagerMock_EnterPid_Call struct {
	*mock.Call
}

// EnterPid is a helper method to define mock.On call
//   - cgroupPaths map[string]string
//   - pid int
func (_e *allCGroupManagerMock_Expecter) EnterPid(cgroupPaths interface{}, pid interface{}) *allCGroupManagerMock_EnterPid_Call {
	return &allCGroupManagerMock_EnterPid_Call{Call: _e.mock.On("EnterPid", cgroupPaths, pid)}
}

func (_c *allCGroupManagerMock_EnterPid_Call) Run(run func(cgroupPaths map[string]string, pid int)) *allCGroupManagerMock_EnterPid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string), args[1].(int))
	})
	return _c
}

func (_c *allCGroupManagerMock_EnterPid_Call) Return(_a0 error) *allCGroupManagerMock_EnterPid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *allCGroupManagerMock_EnterPid_Call) RunAndReturn(run func(map[string]string, int) error) *allCGroupManagerMock_EnterPid_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaths provides a mock function with given fields:
func (_m *allCGroupManagerMock) GetPaths() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// allCGroupManagerMock_GetPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaths'
type allCGroupManagerMock_GetPaths_Call struct {
	*mock.Call
}

// GetPaths is a helper method to define mock.On call
func (_e *allCGroupManagerMock_Expecter) GetPaths() *allCGroupManagerMock_GetPaths_Call {
	return &allCGroupManagerMock_GetPaths_Call{Call: _e.mock.On("GetPaths")}
}

func (_c *allCGroupManagerMock_GetPaths_Call) Run(run func()) *allCGroupManagerMock_GetPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *allCGroupManagerMock_GetPaths_Call) Return(_a0 map[string]string) *allCGroupManagerMock_GetPaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *allCGroupManagerMock_GetPaths_Call) RunAndReturn(run func() map[string]string) *allCGroupManagerMock_GetPaths_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function with given fields: _a0
func (_m *allCGroupManagerMock) Path(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// allCGroupManagerMock_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type allCGroupManagerMock_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
//   - _a0 string
func (_e *allCGroupManagerMock_Expecter) Path(_a0 interface{}) *allCGroupManagerMock_Path_Call {
	return &allCGroupManagerMock_Path_Call{Call: _e.mock.On("Path", _a0)}
}

func (_c *allCGroupManagerMock_Path_Call) Run(run func(_a0 string)) *allCGroupManagerMock_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *allCGroupManagerMock_Path_Call) Return(_a0 string) *allCGroupManagerMock_Path_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *allCGroupManagerMock_Path_Call) RunAndReturn(run func(string) string) *allCGroupManagerMock_Path_Call {
	_c.Call.Return(run)
	return _c
}

// PathExists provides a mock function with given fields: path
func (_m *allCGroupManagerMock) PathExists(path string) bool {
	ret := _m.Called(path)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// allCGroupManagerMock_PathExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PathExists'
type allCGroupManagerMock_PathExists_Call struct {
	*mock.Call
}

// PathExists is a helper method to define mock.On call
//   - path string
func (_e *allCGroupManagerMock_Expecter) PathExists(path interface{}) *allCGroupManagerMock_PathExists_Call {
	return &allCGroupManagerMock_PathExists_Call{Call: _e.mock.On("PathExists", path)}
}

func (_c *allCGroupManagerMock_PathExists_Call) Run(run func(path string)) *allCGroupManagerMock_PathExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *allCGroupManagerMock_PathExists_Call) Return(_a0 bool) *allCGroupManagerMock_PathExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *allCGroupManagerMock_PathExists_Call) RunAndReturn(run func(string) bool) *allCGroupManagerMock_PathExists_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: dir, file
func (_m *allCGroupManagerMock) ReadFile(dir string, file string) (string, error) {
	ret := _m.Called(dir, file)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(dir, file)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(dir, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// allCGroupManagerMock_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type allCGroupManagerMock_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - dir string
//   - file string
func (_e *allCGroupManagerMock_Expecter) ReadFile(dir interface{}, file interface{}) *allCGroupManagerMock_ReadFile_Call {
	return &allCGroupManagerMock_ReadFile_Call{Call: _e.mock.On("ReadFile", dir, file)}
}

func (_c *allCGroupManagerMock_ReadFile_Call) Run(run func(dir string, file string)) *allCGroupManagerMock_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *allCGroupManagerMock_ReadFile_Call) Return(_a0 string, _a1 error) *allCGroupManagerMock_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *allCGroupManagerMock_ReadFile_Call) RunAndReturn(run func(string, string) (string, error)) *allCGroupManagerMock_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: dir, file, data
func (_m *allCGroupManagerMock) WriteFile(dir string, file string, data string) error {
	ret := _m.Called(dir, file, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(dir, file, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// allCGroupManagerMock_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type allCGroupManagerMock_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - dir string
//   - file string
//   - data string
func (_e *allCGroupManagerMock_Expecter) WriteFile(dir interface{}, file interface{}, data interface{}) *allCGroupManagerMock_WriteFile_Call {
	return &allCGroupManagerMock_WriteFile_Call{Call: _e.mock.On("WriteFile", dir, file, data)}
}

func (_c *allCGroupManagerMock_WriteFile_Call) Run(run func(dir string, file string, data string)) *allCGroupManagerMock_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *allCGroupManagerMock_WriteFile_Call) Return(_a0 error) *allCGroupManagerMock_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *allCGroupManagerMock_WriteFile_Call) RunAndReturn(run func(string, string, string) error) *allCGroupManagerMock_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewAllCGroupManagerMock interface {
	mock.TestingT
	Cleanup(func())
}

// newAllCGroupManagerMock creates a new instance of allCGroupManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newAllCGroupManagerMock(t mockConstructorTestingTnewAllCGroupManagerMock) *allCGroupManagerMock {
	mock := &allCGroupManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
