# permissions to do edit disruptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disruption-editor-role
rules:
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - disruptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - disruptions/status
  verbs:
  - get
  - patch
  - update
