# permissions to do viewer networkfailureinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfailureinjection-viewer-role
rules:
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networkfailureinjections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networkfailureinjections/status
  verbs:
  - get
