# permissions to do edit networklatencyinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networklatencyinjection-editor-role
rules:
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networklatencyinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networklatencyinjections/status
  verbs:
  - get
  - patch
  - update
