# permissions to do edit networkfailureinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkfailureinjection-editor-role
rules:
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networkfailureinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - networkfailureinjections/status
  verbs:
  - get
  - patch
  - update
