# permissions to do edit nodefailureinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodefailureinjection-editor-role
rules:
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - nodefailureinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.datadoghq.com
  resources:
  - nodefailureinjections/status
  verbs:
  - get
  - patch
  - update
