// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package network

import (
	mock "github.com/stretchr/testify/mock"
	zap "go.uber.org/zap"
)

// NetlinkAdapterMock is an autogenerated mock type for the NetlinkAdapter type
type NetlinkAdapterMock struct {
	mock.Mock
}

type NetlinkAdapterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NetlinkAdapterMock) EXPECT() *NetlinkAdapterMock_Expecter {
	return &NetlinkAdapterMock_Expecter{mock: &_m.Mock}
}

// DefaultRoutes provides a mock function with given fields:
func (_m *NetlinkAdapterMock) DefaultRoutes() ([]NetlinkRoute, error) {
	ret := _m.Called()

	var r0 []NetlinkRoute
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]NetlinkRoute, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []NetlinkRoute); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NetlinkRoute)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetlinkAdapterMock_DefaultRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultRoutes'
type NetlinkAdapterMock_DefaultRoutes_Call struct {
	*mock.Call
}

// DefaultRoutes is a helper method to define mock.On call
func (_e *NetlinkAdapterMock_Expecter) DefaultRoutes() *NetlinkAdapterMock_DefaultRoutes_Call {
	return &NetlinkAdapterMock_DefaultRoutes_Call{Call: _e.mock.On("DefaultRoutes")}
}

func (_c *NetlinkAdapterMock_DefaultRoutes_Call) Run(run func()) *NetlinkAdapterMock_DefaultRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetlinkAdapterMock_DefaultRoutes_Call) Return(_a0 []NetlinkRoute, _a1 error) *NetlinkAdapterMock_DefaultRoutes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetlinkAdapterMock_DefaultRoutes_Call) RunAndReturn(run func() ([]NetlinkRoute, error)) *NetlinkAdapterMock_DefaultRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// LinkByIndex provides a mock function with given fields: index
func (_m *NetlinkAdapterMock) LinkByIndex(index int) (NetlinkLink, error) {
	ret := _m.Called(index)

	var r0 NetlinkLink
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (NetlinkLink, error)); ok {
		return rf(index)
	}
	if rf, ok := ret.Get(0).(func(int) NetlinkLink); ok {
		r0 = rf(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(NetlinkLink)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetlinkAdapterMock_LinkByIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkByIndex'
type NetlinkAdapterMock_LinkByIndex_Call struct {
	*mock.Call
}

// LinkByIndex is a helper method to define mock.On call
//   - index int
func (_e *NetlinkAdapterMock_Expecter) LinkByIndex(index interface{}) *NetlinkAdapterMock_LinkByIndex_Call {
	return &NetlinkAdapterMock_LinkByIndex_Call{Call: _e.mock.On("LinkByIndex", index)}
}

func (_c *NetlinkAdapterMock_LinkByIndex_Call) Run(run func(index int)) *NetlinkAdapterMock_LinkByIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *NetlinkAdapterMock_LinkByIndex_Call) Return(_a0 NetlinkLink, _a1 error) *NetlinkAdapterMock_LinkByIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetlinkAdapterMock_LinkByIndex_Call) RunAndReturn(run func(int) (NetlinkLink, error)) *NetlinkAdapterMock_LinkByIndex_Call {
	_c.Call.Return(run)
	return _c
}

// LinkByName provides a mock function with given fields: name
func (_m *NetlinkAdapterMock) LinkByName(name string) (NetlinkLink, error) {
	ret := _m.Called(name)

	var r0 NetlinkLink
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (NetlinkLink, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) NetlinkLink); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(NetlinkLink)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetlinkAdapterMock_LinkByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkByName'
type NetlinkAdapterMock_LinkByName_Call struct {
	*mock.Call
}

// LinkByName is a helper method to define mock.On call
//   - name string
func (_e *NetlinkAdapterMock_Expecter) LinkByName(name interface{}) *NetlinkAdapterMock_LinkByName_Call {
	return &NetlinkAdapterMock_LinkByName_Call{Call: _e.mock.On("LinkByName", name)}
}

func (_c *NetlinkAdapterMock_LinkByName_Call) Run(run func(name string)) *NetlinkAdapterMock_LinkByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NetlinkAdapterMock_LinkByName_Call) Return(_a0 NetlinkLink, _a1 error) *NetlinkAdapterMock_LinkByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetlinkAdapterMock_LinkByName_Call) RunAndReturn(run func(string) (NetlinkLink, error)) *NetlinkAdapterMock_LinkByName_Call {
	_c.Call.Return(run)
	return _c
}

// LinkList provides a mock function with given fields: useLocalhost, log
func (_m *NetlinkAdapterMock) LinkList(useLocalhost bool, log *zap.SugaredLogger) ([]NetlinkLink, error) {
	ret := _m.Called(useLocalhost, log)

	var r0 []NetlinkLink
	var r1 error
	if rf, ok := ret.Get(0).(func(bool, *zap.SugaredLogger) ([]NetlinkLink, error)); ok {
		return rf(useLocalhost, log)
	}
	if rf, ok := ret.Get(0).(func(bool, *zap.SugaredLogger) []NetlinkLink); ok {
		r0 = rf(useLocalhost, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NetlinkLink)
		}
	}

	if rf, ok := ret.Get(1).(func(bool, *zap.SugaredLogger) error); ok {
		r1 = rf(useLocalhost, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetlinkAdapterMock_LinkList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkList'
type NetlinkAdapterMock_LinkList_Call struct {
	*mock.Call
}

// LinkList is a helper method to define mock.On call
//   - useLocalhost bool
//   - log *zap.SugaredLogger
func (_e *NetlinkAdapterMock_Expecter) LinkList(useLocalhost interface{}, log interface{}) *NetlinkAdapterMock_LinkList_Call {
	return &NetlinkAdapterMock_LinkList_Call{Call: _e.mock.On("LinkList", useLocalhost, log)}
}

func (_c *NetlinkAdapterMock_LinkList_Call) Run(run func(useLocalhost bool, log *zap.SugaredLogger)) *NetlinkAdapterMock_LinkList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(*zap.SugaredLogger))
	})
	return _c
}

func (_c *NetlinkAdapterMock_LinkList_Call) Return(_a0 []NetlinkLink, _a1 error) *NetlinkAdapterMock_LinkList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetlinkAdapterMock_LinkList_Call) RunAndReturn(run func(bool, *zap.SugaredLogger) ([]NetlinkLink, error)) *NetlinkAdapterMock_LinkList_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewNetlinkAdapterMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewNetlinkAdapterMock creates a new instance of NetlinkAdapterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNetlinkAdapterMock(t mockConstructorTestingTNewNetlinkAdapterMock) *NetlinkAdapterMock {
	mock := &NetlinkAdapterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
