---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    app: {{ $.Chart.Name }}
    chart_name: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
    service: {{ $.Chart.Name }}
    team: {{ $.Values.team }}
  name: chaos-fi-controller-controller-manager
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: chaos-fi-controller-controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
        app: {{ $.Chart.Name }}
        chart_name: {{ $.Chart.Name }}
        chart_version: {{ $.Chart.Version }}
        service: {{ $.Chart.Name }}
        team: {{ $.Values.team }}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: chaos-fi-controller-webhook-server-secret
        image: "{{ $.Values.global.docker.registry }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: chaos-fi-controller-webhook-server-secret
