// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2024 Datadog, Inc.
package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// StatFSMock is an autogenerated mock type for the StatFS type
type StatFSMock struct {
	mock.Mock
}

type StatFSMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StatFSMock) EXPECT() *StatFSMock_Expecter {
	return &StatFSMock_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: name
func (_m *StatFSMock) Open(name string) (fs.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatFSMock_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type StatFSMock_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *StatFSMock_Expecter) Open(name interface{}) *StatFSMock_Open_Call {
	return &StatFSMock_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *StatFSMock_Open_Call) Run(run func(name string)) *StatFSMock_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StatFSMock_Open_Call) Return(_a0 fs.File, _a1 error) *StatFSMock_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatFSMock_Open_Call) RunAndReturn(run func(string) (fs.File, error)) *StatFSMock_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *StatFSMock) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatFSMock_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type StatFSMock_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *StatFSMock_Expecter) Stat(name interface{}) *StatFSMock_Stat_Call {
	return &StatFSMock_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *StatFSMock_Stat_Call) Run(run func(name string)) *StatFSMock_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StatFSMock_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *StatFSMock_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatFSMock_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *StatFSMock_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatFSMock creates a new instance of StatFSMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatFSMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatFSMock {
	mock := &StatFSMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
