// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package mocks

import mock "github.com/stretchr/testify/mock"

// StresserMock is an autogenerated mock type for the Stresser type
type StresserMock struct {
	mock.Mock
}

type StresserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StresserMock) EXPECT() *StresserMock_Expecter {
	return &StresserMock_Expecter{mock: &_m.Mock}
}

// Stress provides a mock function with given fields: exit
func (_m *StresserMock) Stress(exit <-chan struct{}) {
	_m.Called(exit)
}

// StresserMock_Stress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stress'
type StresserMock_Stress_Call struct {
	*mock.Call
}

// Stress is a helper method to define mock.On call
//   - exit <-chan struct{}
func (_e *StresserMock_Expecter) Stress(exit interface{}) *StresserMock_Stress_Call {
	return &StresserMock_Stress_Call{Call: _e.mock.On("Stress", exit)}
}

func (_c *StresserMock_Stress_Call) Run(run func(exit <-chan struct{})) *StresserMock_Stress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(<-chan struct{}))
	})
	return _c
}

func (_c *StresserMock_Stress_Call) Return() *StresserMock_Stress_Call {
	_c.Call.Return()
	return _c
}

func (_c *StresserMock_Stress_Call) RunAndReturn(run func(<-chan struct{})) *StresserMock_Stress_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStresserMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewStresserMock creates a new instance of StresserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStresserMock(t mockConstructorTestingTNewStresserMock) *StresserMock {
	mock := &StresserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
