# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-drop
  namespace: chaos-demo-1
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  network:
    drop: 100 # percentage of outgoing packets to drop
    nodes:
      - selector:
          topology.kubernetes.io/zone: us-east-1b
    pods:
      - selector: # service name
          app: demo-nginx
