apiVersion: v1
kind: Namespace
metadata:
  name: chaos-demo-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: chaos-demo-2
  labels:
    app: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minikube-m02
      containers:
        - name: nginx
          image: nginx:1.21.6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 50m
              memory: 30Mi
            requests:
              cpu: 50m
              memory: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-curl
  namespace: chaos-demo-2
  labels:
    app: demo-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-curl
  template:
    metadata:
      labels:
        app: demo-curl
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minikube-m02
      containers:
        - name: curl
          image: alpine/curl:3.14
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://demo.chaos-demo-2.svc.cluster.local:8080; sleep 1; done",
            ]
        - name: dummy
          image: ubuntu:bionic-20220128
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: chaos-demo-2
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: demo-nginx
