# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
spec:
  selector: # label selector to target pods
    app: demo
  count: 1 # number of pods to target (if set to 0 or not specified, it'll select all pods)
  networkFailure: # packet loss and connection drop
    hosts:
      - 10.0.0.0/8 # destination host
    probability: 100 # probability to drop packets
    port: 80 # port to drop packets on
    protocol: tcp # protocol to drop packets on (can be tcp or udp)
  networkLatency: # network latency
    delay: 1000 # delay in ms
    hosts: # destination hosts to add latency to
      - 10.0.0.0/8
