apiVersion: chaos.datadoghq.com/v1beta1
kind: DependencyFailureInjection
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: dependencyfailureinjection-sample
  namespace: sre
spec:
  failure:
    host: chaos-fi-demo.sre.svc.barbet.cluster.local
    port: 80
    probability: 50
    protocol: tcp
  labelSelector: "app=chaos-fi-demo-curl"
