# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
  namespace: default # disruption resource must be in the same namespace as targeted pods
spec:
  selector: # label selector to target pods
    app: demo
  count: 1 # number of pods to target (-1 == target all the selected pods)
  networkFailure: # packet loss and connection
    corrupt: 100 # probability to drop packets (between 0 and 100)
    drop: 0
    port: 8080 # port to drop packets on
    corrupt: 0
    protocol: tcp # protocol to drop packets on (can be tcp or udp)
    allowEstablishment: false # allow connection to be established before dropping packets (drops established connections packets only)
