# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
spec:
  generalSelector: # general selector to target pods
    app: demo
  specSelector: # area zone selector to target pods
    #The following configs are currently supported:
    #failure-domain.beta.kubernetes.io/zone
    #topology.kubernetes.io/zone:
    azSelector:
      - us-east-1a
  count: 1 # number of pods to target (-1 == target all the selected pods)
  networkFailure: # packet loss and connection drop
    hosts:
      - 10.0.0.0/8 # destination host
    probability: 100 # probability to drop packets
    port: 80 # port to drop packets on
    protocol: tcp # protocol to drop packets on (can be tcp or udp)
  networkLatency: # network latency
    delay: 1000 # delay in ms
    hosts: # destination hosts to add latency to
      - 10.0.0.0/8
  nodeFailure: # node kernel panic or shutdown
    shutdown: true # shutdown the host instead of triggering a stack dump
