apiVersion: chaos.datadoghq.com/v1beta1
kind: NetworkFailureInjection
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: networkfailureinjection-sample
spec:
  failure:
    host: 10.0.0.0/8
    port: 80
    probability: 100
    protocol: tcp
  selector:
    app: demo
  numPodsToTarget: 1
