# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
  namespace: chaos-engineering # disruption resource must be in the same namespace as targeted pods
spec:
  selector: # label selector to target pods
    app: demo
  count: 1 # number of pods to target (-1 == target all the selected pods)
  nodeFailure: # node kernel panic or shutdown
    shutdown: true # shutdown the host instead of triggering a stack dump
  network: # network disruption settings
    hosts:
      - 10.0.0.0/8 # destination host
    port: 80 # port to drop packets on
    protocol: tcp # protocol to drop packets on (can be tcp or udp)
    drop: 10 # probability to drop packets (between 0 and 100)
    corrupt: 5 # probability to corrupt packets (between 0 and 100)
    delay: 1000 # latency to apply to packets in ms
    bandwidthLimit: 10000 # bandwidth limit in bytes
  cpuPressure: {} # cpu load generator
  diskPressure: # disk pressure
    path: /mnt/data # mount point (in the pod) to apply throttle on
    throttling:
      readBytesPerSec: 1024 # read throttling in bytes per sec
      writeBytesPerSec: 2048 # write throttling in bytes per sec
