# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
  namespace: chaos-engineering # disruption resource must be in the same namespace as targeted pods
spec:
  dryRun: false # optional, enable dry-run mode (chaos pods will be created but won't inject anything)
  level: pod # level the disruption should be injected at (can be either pod or node, defaults to pod)
  selector: # label selector to target pods
    app: demo
  container: demo1 # optional, name of the container to target within the targeted pod
  count: 1 # number of pods to target or a percentage (1% - 100%)
  nodeFailure: # node kernel panic or shutdown
    shutdown: true # optional, shutdown the host instead of triggering a stack dump (defaults to false)
  network: # network disruption settings, all those disruptions are applied to outgoing traffic only
    hosts: # optional (targets all hosts if not specified)
      - 10.0.0.0/8 # destination host
    port: 80 # optional, port to drop packets on
    protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
    flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
    drop: 10 # optional, probability to drop packets (between 0 and 100)
    corrupt: 5 # optional, probability to corrupt packets (between 0 and 100m)
    delay: 1000 # optional, latency to apply to packets in ms
    delayJitter: 5 # optional, add X % (1-100) of delay as jitter to delay (+- X% ms to original delay), defaults to 10%
    bandwidthLimit: 10000 # optional, bandwidth limit in bytes
  cpuPressure: {} # cpu load generator
  diskPressure: # disk pressure
    path: /mnt/data # mount point (in the pod) to apply throttle on
    throttling:
      readBytesPerSec: 1024 # optional, read throttling in bytes per sec
      writeBytesPerSec: 2048 # optional, write throttling in bytes per sec
