# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: chaos-engineering
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ubuntu:bionic
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 10000; done"]
        volumeMounts:
        - mountPath: /mnt/data
          name: data
        resources:
          limits:
            cpu: 1
      - name: demo2
        image: ubuntu:bionic
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 10000; done"]
        volumeMounts:
        - mountPath: /mnt/data
          name: data
        resources:
          limits:
            cpu: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo
