---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: alpine
        command: ["sh"]
        args:
          - "-c"
          - "sleep 100000000"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        #image: k8s.gcr.io/pause:3.1
