# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-filters
  namespace: chaos-engineering
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  network:
    drop: 100
    hosts:
      - host: 1.2.3.4 # host can be a single IP
      - host: 10.0.0.0/8 # or it can be a CIDR
        port: 80 # if not specified, all ports are targeted
      - host: datadoghq.com # or it can be a hostname (then all the resolved IP will be taken)
        port: 443
        protocol: tcp # if not specified, tcp and udp are targeted
