# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-drop
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  filter:
    annotations:
      app.kubernetes.io/component: client # filter selected targets to only those with this annotation
  count: 1
  network:
    drop: 100
