# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disruption-sample
  namespace: chaos-demo # disruption resource must be in the same namespace as targeted pods
spec:
  dryRun: false # optional, enable dry-run mode (chaos pods will be created but won't inject anything)
  level: pod # level the disruption should be injected at (can be either pod or node, defaults to pod)
  selector: # label selector[s] to target pods
    app: demo
    team: developer
  advancedSelector: # advanced selectors can select targets on something else than an exact key/value match
    - key: app
      operator: Exists
  # - key: app
  #   operator: DoesNotExist
  # - key: app
  #   operator: In
  #   values:
  #     - curl
  # - key: app
  #   operator: NotIn
  #   values:
  #     - nginx
  containers: # optional, name of the containers to target within the targeted pod, by default all pods are targeted
    - demo
    - demo2
  count: 1 # number of pods to target or a percentage (1% - 100%)
  nodeFailure: # node kernel panic or shutdown
    shutdown: true # optional, shutdown the host instead of triggering a stack dump (defaults to false)
  containerFailure: # terminating a pod's containers gracefully or non-gracefully
    forced: true # optional, terminate the pod's containers non-gracefully (SIGKILL) (defaults to false)
  network: # network disruption settings, all those disruptions are applied to outgoing traffic only
    hosts: # optional, list of destination hosts to filter on
      - host: 10.0.0.0/8 # optional, IP, CIDR or hostname to filter on
        port: 80 # optional, port to drop packets on
        protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
    allowedHosts: # optional, list of excluded hosts which would not be disrupted
      - host: 10.0.0.1 # optional, IP, CIDR or hostname to filter on
        port: 80 # optional, port to filter on
        protocol: tcp # optional, protocol to filter on (can be tcp or udp, defaults to both)
    services: # optional, list of destination Kubernetes services to filter on
      - name: foo # service name
        namespace: bar # service namespace
    flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
    drop: 10 # "mandatory", at least one of `bandwidthLimit`, `delay`, `drop`, `corrupt`, or `duplicate` must be specified; probability to drop packets (between 0 and 100)
    corrupt: 5 # probability to corrupt packets (between 0 and 100)
    delay: 1000 # latency to apply to packets in ms
    delayJitter: 5 # add X % (1-100) of delay as jitter to delay (+- X% ms to original delay), defaults to 10%
    bandwidthLimit: 10000 # bandwidth limit in bytes
  cpuPressure: {} # cpu load generator
  diskPressure: # disk pressure
    path: /mnt/data # mount point (in the pod) to apply throttle on
    throttling:
      readBytesPerSec: 1024 # optional, read throttling in bytes per sec
      writeBytesPerSec: 2048 # optional, write throttling in bytes per sec
  dns: # disrupt DNS resolutions by faking results
    - hostname: foo.bar.svc.cluster.local # record hostname which should be faked
      record:
        type: A # return an A record
        value: 10.0.0.154,10.0.0.13 # list of IPs to return (will be round-robined)
    - hostname: datadoghq.com # record hostname which should be faked
      record:
        type: CNAME # return a CNAME record
        value: google.com # hostname to return
  grpc: # disrupt gRPC responses by faking results
    port: 50051 # port to disrupt
    endpoints:
      - endpoint: /chaos_dogfood.ChaosDogfood/getCatalog # gRPC service endpoint to disrupt
        error: NOT_FOUND # gRPC error code to return instead computed response
        queryPercent: 10 # percentage to affect (1-100); multiple alterations allowed for single endpoint, but sum should not exceed 100%
      - endpoint: /chaos_dogfood.ChaosDogfood/order # gRPC service endpoint to disrupt
        override: "{}" # response structure to return instead of computed response - currently only returns emptypb.Empty
        queryPercent: 50 # percentage to affect (1-100); multiple alterations allowed for single endpoint, but sum should not exceed 100%
      - endpoint: /chaos_dogfood.ChaosDogfood/order # gRPC service endpoint to disrupt
        error: PERMISSION_DENIED # gRPC error code to return instead computed response
        # unspecified queryPercent: an endpoint with Y[1], Y[2],...Y[X] explicit queryPercents and Y[X+1],...Y[X+N] other alterations defaults to (100 - SUM(Y[1] +..+ Y[X])) / N %
