# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: container-failure-graceful
  namespace: chaos-demo
spec:
  selector:
    app: demo-curl
  containers: # only target the curl container, you can specify multiple containers here (all containers are targeted by default)
    - curl
  count: 1
  containerFailure:
    forced: false # send a SIGTERM signal to the specified containers
