# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: count-percentage
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 50% # target a percentage of the targets matching the selector instead of a fixed count (will be rounded up, min 1%, max 100%)
  nodeFailure:
    shutdown: false
