# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: level-node
  namespace: chaos-demo
spec:
  level: node # impact the whole node instead of a single pod
  selector:
    node.kubernetes.io/instance-type: k3s # when node level is enabled, the selector applies to nodes and not pods
  count: 1
  cpuPressure: {}
