# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: cpu-pressure
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  cpuPressure:
    count: 1 # stress ALL CORES for at most 1/CORE_COUNT percentage
