# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-curl
  namespace: chaos-demo
  labels:
    app: demo-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-curl
  template:
    metadata:
      labels:
        app: demo-curl
    spec:
      containers:
        - name: curlcluster80
          image: appropriate/curl
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://demo.chaos-demo.svc.cluster.local:80; sleep 1; done",
            ]
          volumeMounts:
            - mountPath: /mnt/data
              name: data
          resources:
            limits:
              cpu: 1
        - name: curlcluster8080
          image: appropriate/curl
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://demo.chaos-demo.svc.cluster.local:8080; sleep 1; done",
            ]
          volumeMounts:
            - mountPath: /mnt/data
              name: data
          resources:
            limits:
              cpu: 1
        - name: curlpod8080
          image: appropriate/curl
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://10.244.0.8:8080; sleep 1; done",
            ]
        - name: curlpod80
          image: appropriate/curl
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do curl -vvv http://10.244.0.8:80; sleep 1; done",
            ]
        - name: dummy
          image: ubuntu:bionic
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 1; done"]
          volumeMounts:
            - mountPath: /mnt/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: demo
