# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: dns
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  dns: # disrupt DNS resolutions by faking results
    - hostname: foo.bar.svc.cluster.local # record hostname which should be faked
      record:
        type: A # return an A record
        value: 10.0.0.154,10.0.0.13 # list of IPs to return (will be round-robined)
    - hostname: datadoghq.com # record hostname which should be faked
      record:
        type: CNAME # return a CNAME record
        value: google.com # hostname to return
