# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: dry-run-node-hello
  namespace: chaos-engineering
spec:
  dryRun: true # enable dry-run mode (chaos pods will be created but won't inject anything)
  level: node
  selector:
    kubernetes.io/os: linuxxxxx
  count: 1
  staticTargeting: false
  network:
    delay: 10 # delay (in milliseconds) to add to outgoing packets, 10% of jitter will be added by default
    delayJitter: 5 # (optional) add X % (1-100) of delay as jitter to delay (+- X% ms to original delay), defaults to 10%
