# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: grpc
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: chaos-dogfood-server
  count: 100%
  grpc:
    port: 50051
    endpoints:
      - endpoint: /chaos_dogfood.ChaosDogfood/getCatalog
        error: NOT_FOUND
        query_pct: 25
      - endpoint: /chaos_dogfood.ChaosDogfood/getCatalog
        error: ALREADY_EXISTS
        query_pct: 50
      - endpoint: /chaos_dogfood.ChaosDogfood/getCatalog
        override: "{}"
      - endpoint: /chaos_dogfood.ChaosDogfood/order
        override: "{}"
        query_pct: 50
