# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

# Warning! The grpc disruption is unique. You will need to follow the linked docs:
# https://github.com/DataDog/chaos-controller/blob/main/docs/grpc_disruption/instructions.md
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: grpc-override
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: chaos-dogfood-server
  count: 100%
  grpc:
    port: 50050
    endpoints:
      - endpoint: /chaosdogfood.ChaosDogfood/getCatalog # gRPC service endpoint to disrupt
        override: "{}" # response structure to return instead of computed response - currently only returns emptypb.Empty
      - endpoint: /chaosdogfood.ChaosDogfood/order # gRPC service endpoint to disrupt
        override: "{}" # response structure to return instead of computed response - currently only returns emptypb.Empty
