apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: memory-pressure
  namespace: chaos-demo
spec:
  level: pod
  selector:
    service: demo-curl
  count: 100%
  duration: 5m
  memoryPressure:
    targetPercent: "50%"
    #rampDuration: 10m
