# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: memory-pressure
  namespace: chaos-demo
spec:
  level: pod
  selector:
    service: demo-curl
  count: 100%
  duration: 5m
  memoryPressure:
    targetPercent: "50%"
    #rampDuration: 10m
