# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-duplication
  namespace: chaos-demo
spec:
  selector:
    service: demo-curl
  count: 1
  network:
    duplicate: 100 # percentage of outgoing packets to duplicate
