# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-cloud
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  network:
    cloud:
      gcp:
        - service: "Google" # service name as declared in the provider file (see doc for details)
    drop: 100 # percentage of outgoing packets to drop
