# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-delay
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  network:
    drop: 100 # delay (in milliseconds) to add to outgoing packets, 10% of jitter will be added by default
