# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-filter-service
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  network:
    drop: 100
    services: # filter on Kubernetes services; this will correctly handle the port differences in node vs. pod-level disruptions
      - name: demo # service name
        namespace: chaos-demo # service namespace
        ports: # optional. List of affected ports. No list means all ports are affected
          - name: regular-port # optional. Name of the port, used to identify the port affected. You need to specify at least one of each name or port.
            port: 8080 # optional. Value of the port, used to identify the port affected.
          - port: 8081
