# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-cloud
  namespace: chaos-demo
  annotations:
    chaos.datadoghq.com/environment: "lima"
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  network:
    cloud:
      aws:
        - service: "S3" # service name as declared in the provider file (see doc for details)
          protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
          flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
          connState: new # optional, connection state (new: new connections, est: established connections, defaults to all states)
      gcp:
        - service: "Google" # service name as declared in the provider file (see doc for details)
          protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
          flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
          connState: new # optional, connection state (new: new connections, est: established connections, defaults to all states)
      datadog:
        - service: "synthetics" # service name as declared in the provider file (see doc for details)
          protocol: tcp # optional, protocol to drop packets on (can be tcp or udp, defaults to both)
          flow: ingress # optional, flow direction (egress: outgoing traffic, ingress: incoming traffic, defaults to egress)
          connState: new # optional, connection state (new: new connections, est: established connections, defaults to all states)
    drop: 100 # percentage of outgoing packets to drop
