# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: node-replacement
  namespace: chaos-demo # it must be in the same namespace as targeted resources
spec:
  level: pod # selector targets pods. Targeting a pod will impact the node hosting given pod.
  selector:
    app: demo-storage # target the StatefulSet pod which will auto-recreate its PVC
  count: 1
  duration: 5m # duration for the disruption to remain active
  maxRuns: 1 # perform only 1 node replacement, then become idle
  nodeReplacement: # replace the target node by cordoning, deleting PVCs, and killing pods
    deleteStorage: true # delete PVCs associated with pods (default: true)
    forceDelete: true # force delete pods with grace period 0 (default: false)
    gracePeriodSeconds: 30 # grace period for pod deletion in seconds (optional)
