# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: node-failure-shutdown
  namespace: chaos-demo
  annotations:
    chaos.datadoghq.com/environment: "lima"
spec:
  level: node # selector targets nodes instead of pods. Targeting a pod will impact the node hosting given pod.
  selector:
    app: demo-curl
  count: 1
  nodeFailure:
    shutdown: true # shutdown the host (violently) instead of triggering a kernel panic so the host is kept down and not restarted
