# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: disk-failure
  namespace: chaos-demo
spec:
  level: node # impact the whole node instead of a single pod
  selector:
    kubernetes.io/hostname: lima-default # when node level is enabled, the selector applies to nodes and not pods
  #level: pod
  #selector:
  #  app: demo-curl
  count: 1
  #containers: # only target the dummy container, you can specify multiple containers here (all containers are targeted by default)
  #  - read-file
  diskFailure:
    path: /
