# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: pulse
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  duration: 10m
  pulse: # optional, activate pulsing disruptions. Available for any disruptions except nodeFailure and containerFailure
    initialDelay: 1m # optional field. Injectors will sleep for this long before beginning the first activeDuration
    activeDuration: 60s # this is the duration of the disruption in an active state, must be a valid time.Duration string, e.g. (300s, 15m25s, 4h) and must be greater than 500ms
    dormantDuration: 20s # this is the duration of the disruption in a dormant state, must be a valid time.Duration string, e.g. (300s, 15m25s, 4h) and must be greater than 500ms
  network:
    drop: 100
