# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-drop
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: demo-curl
  count: 1
  duration: 15s # Disruption will time out after 1800s (30m)
  network:
    delay: 300
