# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2023 Datadog, Inc.

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-delay
  namespace: chaos-demo
  annotations:
    chaos.datadoghq.com/environment: "lima"
spec:
  level: pod
  selector:
    app: demo-curl
  count: 100%
  staticTargeting: true
  trigger:
    inject:
      # notBefore: rfc3339 # TODO
      offset: 2m
    pods:
      # notBefore: rfc3339 # TODO
      offset: 1m # TODO ignored
  containerFailure:
    forced: true
