# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.io/chaos-dogfood-client"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
fullname: "chaos-dogfood-client"
namespace: "chaos-demo"

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []
