// Code generated by mockery. DO NOT EDIT.

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.
package disk

import mock "github.com/stretchr/testify/mock"

// MockInformer is an autogenerated mock type for the Informer type
type MockInformer struct {
	mock.Mock
}

type MockInformer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInformer) EXPECT() *MockInformer_Expecter {
	return &MockInformer_Expecter{mock: &_m.Mock}
}

// Major provides a mock function with given fields:
func (_m *MockInformer) Major() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockInformer_Major_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Major'
type MockInformer_Major_Call struct {
	*mock.Call
}

// Major is a helper method to define mock.On call
func (_e *MockInformer_Expecter) Major() *MockInformer_Major_Call {
	return &MockInformer_Major_Call{Call: _e.mock.On("Major")}
}

func (_c *MockInformer_Major_Call) Run(run func()) *MockInformer_Major_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInformer_Major_Call) Return(_a0 int) *MockInformer_Major_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInformer_Major_Call) RunAndReturn(run func() int) *MockInformer_Major_Call {
	_c.Call.Return(run)
	return _c
}

// Source provides a mock function with given fields:
func (_m *MockInformer) Source() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockInformer_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type MockInformer_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *MockInformer_Expecter) Source() *MockInformer_Source_Call {
	return &MockInformer_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *MockInformer_Source_Call) Run(run func()) *MockInformer_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInformer_Source_Call) Return(_a0 string) *MockInformer_Source_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInformer_Source_Call) RunAndReturn(run func() string) *MockInformer_Source_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockInformer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInformer creates a new instance of MockInformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInformer(t mockConstructorTestingTNewMockInformer) *MockInformer {
	mock := &MockInformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
