/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// NetworkFailureInjectionSpec defines the desired state of NetworkFailureInjection
type NetworkFailureInjectionSpec struct {
	Failure  NetworkFailureInjectionSpecFailure `json:"failure"`
	Selector labels.Set                         `json:"selector"`
	// Note: the +optional should eventually be generated by the scaffolding, see https://github.com/kubernetes-sigs/kubebuilder/issues/479
	// +optional
	// +kubebuilder:validation:Minimum=0
	NumPodsToTarget *int `json:"numPodsToTarget,omitempty"`
}

// NetworkFailureInjectionSpecFailure defines the failure spec
type NetworkFailureInjectionSpecFailure struct {
	Host        string `json:"host,omitempty"`
	Port        int    `json:"port"`
	Probability int    `json:"probability"`
	Protocol    string `json:"protocol"`
}

// NetworkFailureInjectionStatus defines the observed state of NetworkFailureInjection
type NetworkFailureInjectionStatus struct {
	Finalizing bool     `json:"finalizing"`
	Injected   bool     `json:"injected"`
	Pods       []string `json:"pods,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkFailureInjection is the Schema for the networkfailureinjections API
// +kubebuilder:resource:shortName=nfi
type NetworkFailureInjection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkFailureInjectionSpec   `json:"spec,omitempty"`
	Status NetworkFailureInjectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkFailureInjectionList contains a list of NetworkFailureInjection
type NetworkFailureInjectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkFailureInjection `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NetworkFailureInjection{}, &NetworkFailureInjectionList{})
}
