#!/usr/bin/env bash

function usage() {
  echo "wrong number of parameters: $0 POD_NAME"
  exit 1
}

function exec_into_pod() {
  pod=$1
  cmd=$2
  runtime=${3:-containerd}
  if [[ -z "$pod" ]]; then
    exit 1
  fi
  if [[ -z "$cmd" ]]; then
    exit 2
  fi

  # get container id
  id=$(kubectl -n chaos-engineering get -ojson pod "$pod" | jq -r '.status.containerStatuses[0].containerID' | sed "s#$runtime://##")
  # get pid with containerd
  if [[ "$runtime" = "containerd" ]]; then
    inspect=$(colima ssh -- sudo crictl inspect "$id")
    pid=$(echo "$inspect" | jq -r .info.pid)
  # get pid with docker
  elif [[ "$runtime" = "docker" ]]; then
    inspect=$(colima ssh -- sudo docker inspect "$id")
    pid=$(echo "$inspect" | jq -r '.[0].State.Pid')
  fi

  if [[ -z "$pid" ]]; then
    echo "No pid found for pod $pod. Check runtime"
    exit 1
  fi

  # shellcheck disable=SC2086
  # word splitting is expected on $cmd
  colima ssh -- sudo nsenter --net="/proc/$pid/ns/net" $cmd
}
