# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020 Datadog, Inc.

# This file is for teaching kustomize how to substitute name and namespace reference in CRD
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    path: spec/conversion/webhookClientConfig/service/name

namespace:
- kind: CustomResourceDefinition
  group: apiextensions.k8s.io
  path: spec/conversion/webhookClientConfig/service/namespace
  create: false

varReference:
- path: metadata/annotations
