// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package disruption_listener

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DisruptionListenerClient is the client API for DisruptionListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisruptionListenerClient interface {
	SendDisruption(ctx context.Context, in *DisruptionSpec, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DisruptionStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisruptionSpec, error)
	CleanDisruption(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type disruptionListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewDisruptionListenerClient(cc grpc.ClientConnInterface) DisruptionListenerClient {
	return &disruptionListenerClient{cc}
}

func (c *disruptionListenerClient) SendDisruption(ctx context.Context, in *DisruptionSpec, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/disruption_listener.DisruptionListener/SendDisruption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disruptionListenerClient) DisruptionStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisruptionSpec, error) {
	out := new(DisruptionSpec)
	err := c.cc.Invoke(ctx, "/disruption_listener.DisruptionListener/DisruptionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disruptionListenerClient) CleanDisruption(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/disruption_listener.DisruptionListener/CleanDisruption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisruptionListenerServer is the server API for DisruptionListener service.
// All implementations must embed UnimplementedDisruptionListenerServer
// for forward compatibility
type DisruptionListenerServer interface {
	SendDisruption(context.Context, *DisruptionSpec) (*emptypb.Empty, error)
	DisruptionStatus(context.Context, *emptypb.Empty) (*DisruptionSpec, error)
	CleanDisruption(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedDisruptionListenerServer()
}

// UnimplementedDisruptionListenerServer must be embedded to have forward compatible implementations.
type UnimplementedDisruptionListenerServer struct {
}

func (UnimplementedDisruptionListenerServer) SendDisruption(context.Context, *DisruptionSpec) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDisruption not implemented")
}
func (UnimplementedDisruptionListenerServer) DisruptionStatus(context.Context, *emptypb.Empty) (*DisruptionSpec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisruptionStatus not implemented")
}
func (UnimplementedDisruptionListenerServer) CleanDisruption(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanDisruption not implemented")
}
func (UnimplementedDisruptionListenerServer) mustEmbedUnimplementedDisruptionListenerServer() {}

// UnsafeDisruptionListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisruptionListenerServer will
// result in compilation errors.
type UnsafeDisruptionListenerServer interface {
	mustEmbedUnimplementedDisruptionListenerServer()
}

func RegisterDisruptionListenerServer(s grpc.ServiceRegistrar, srv DisruptionListenerServer) {
	s.RegisterService(&DisruptionListener_ServiceDesc, srv)
}

func _DisruptionListener_SendDisruption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisruptionSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisruptionListenerServer).SendDisruption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disruption_listener.DisruptionListener/SendDisruption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisruptionListenerServer).SendDisruption(ctx, req.(*DisruptionSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisruptionListener_DisruptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisruptionListenerServer).DisruptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disruption_listener.DisruptionListener/DisruptionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisruptionListenerServer).DisruptionStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisruptionListener_CleanDisruption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisruptionListenerServer).CleanDisruption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disruption_listener.DisruptionListener/CleanDisruption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisruptionListenerServer).CleanDisruption(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DisruptionListener_ServiceDesc is the grpc.ServiceDesc for DisruptionListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisruptionListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disruption_listener.DisruptionListener",
	HandlerType: (*DisruptionListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDisruption",
			Handler:    _DisruptionListener_SendDisruption_Handler,
		},
		{
			MethodName: "DisruptionStatus",
			Handler:    _DisruptionListener_DisruptionStatus_Handler,
		},
		{
			MethodName: "CleanDisruption",
			Handler:    _DisruptionListener_CleanDisruption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disruption_listener.proto",
}
